version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: airflow_local
        restart: always
        depends_on:
            - postgres
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__FERNET_KEY=Ri6k4AsPpIhyXSxhEzhdY_W1oEF9BblkMbfeRLM7GWg= # your fernet
            - AIRFLOW_ADMIN_USER=admin # your user
            - AIRFLOW_ADMIN_PASSWORD=12345 # your pass
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432 # your port
            - POSTGRES_USER=airflow # your user
            - POSTGRES_PASSWORD=airflow # your pass
            - POSTGRES_DB=airflow # your db
            - PYTHONPATH=/usr/local/airflow/plugins
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver 
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3